language: go

go:
  - 1.x
  - master

matrix:
  allow_failures:
    - go: master

install:
  - make install

script:
  - make test-ci

notifications:
  email:
    on_success: never
    on_failure: always

env:
  global:
    - MAKEFLAGS=" -j 2"
