language: go
before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install
script:
  - $GOPATH/bin/goveralls -v -service=travis-ci
  - $GOPATH/bin/gometalinter github.com/bradleyjkemp/cupaloy/...
notifications:
  email: false
