language: go

go:
  - 1.8.x
  - 1.x
  - master

matrix:
  allow_failures:
    - go: master
    - go: 1.8.x

install:
  - make install

script:
  - make test-ci

notifications:
  email: false

env:
  global:
    - MAKEFLAGS=" -j 2"
